###
POST http://localhost:5000/usuario/addInvoice HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDc5MDE5OCwianRpIjoiZWNhMDNlNmEtNDM4OC00Mjc3LWEzNDctZDFlYzg2MjhjZDRjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY1ZjMwYjVhNzE1OTUwMGJhYjJmMjliNiIsIm5iZiI6MTcxMDc5MDE5OCwiY3NyZiI6ImU5NTBhYzk4LWU4NjAtNDI3Yi05ZmY4LWVkODk4OWViMWNhNiIsImV4cCI6MTcxMDc5Mzc5OH0.KF5ItrEIgFBNkDCjZ9SXiPcKWLfnL8uqgCtPTgcThFg


{
  "lugar_compra": "olimpica",
  "productos": [
    {
      "categoria": "Alimentos",
      "nombre": "Cafe",
      "cantidad": 1,
      "unidad": "kg",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    },
    {
      "categoria": "Alimentos",
      "nombre": "Arroz",
      "cantidad": 1,
      "unidad": "kg",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    },
    {
      "categoria": "Alimentos",
      "nombre": "Azucar",
      "cantidad": 1,
      "unidad": "kg",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    }
  ]
}



###
GET http://localhost:5000/usuario/getInvoices HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDc5MDE5OCwianRpIjoiZWNhMDNlNmEtNDM4OC00Mjc3LWEzNDctZDFlYzg2MjhjZDRjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY1ZjMwYjVhNzE1OTUwMGJhYjJmMjliNiIsIm5iZiI6MTcxMDc5MDE5OCwiY3NyZiI6ImU5NTBhYzk4LWU4NjAtNDI3Yi05ZmY4LWVkODk4OWViMWNhNiIsImV4cCI6MTcxMDc5Mzc5OH0.KF5ItrEIgFBNkDCjZ9SXiPcKWLfnL8uqgCtPTgcThFg

###
GET  http://localhost:5000/usuario/getInvoices/65f31cd3ea4bdcfbdf1827d0 HTTP/1.1
Content-Type: application/json65f30e6726db0e8354c9ef0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDQzODA4MiwianRpIjoiMjM4MTBkMjUtMzdjNy00ODMyLTlmZjgtZWEyY2VmYjc0ZWMzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY1ZjFhMmE5YzAyYjdlYWQ3MjZkOTFlMCIsIm5iZiI6MTcxMDQzODA4MiwiY3NyZiI6ImE1MzIzODZhLTkxMzUtNDQzMC04MGJiLWFhN2JkZGUyZGEwMCIsImV4cCI6MTcxMDQ0MTY4Mn0.F9LXChWwghKTEYRXcMsUzwlGjGC5t00L9pm_FY3YYJw

###
DELETE  http://localhost:5000/usuario/deleteInvoice/65f8965168b963427c916173 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDc5MDE5OCwianRpIjoiZWNhMDNlNmEtNDM4OC00Mjc3LWEzNDctZDFlYzg2MjhjZDRjIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY1ZjMwYjVhNzE1OTUwMGJhYjJmMjliNiIsIm5iZiI6MTcxMDc5MDE5OCwiY3NyZiI6ImU5NTBhYzk4LWU4NjAtNDI3Yi05ZmY4LWVkODk4OWViMWNhNiIsImV4cCI6MTcxMDc5Mzc5OH0.KF5ItrEIgFBNkDCjZ9SXiPcKWLfnL8uqgCtPTgcThFg

###
PUT  http://localhost:5000/usuario/invoices/65f873c6f363e2a46ef9f8fc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcxMDc4MTE4NywianRpIjoiYjc3NzkxZmUtODU5MC00NTNiLWE2MDMtYjJhYjlhY2FkMDA4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjY1ZjFhMmE5YzAyYjdlYWQ3MjZkOTFlMCIsIm5iZiI6MTcxMDc4MTE4NywiY3NyZiI6IjNhM2VlYmNhLTJhY2QtNGZlNC1iMzM3LTUzY2Q5ODFmOTk3MSIsImV4cCI6MTcxMDc4NDc4N30.X6T-AtnxPo1ue3B_efDG_7uNB_AsUtHylNBcPYNxj-4

{
  "lugar_compra": "olimpica",
  "productos": [
    {
      "categoria": "Alimentos",
      "nombre": "Cafe",
      "cantidad": 1,
      "unidad": "bolsa 150 gr",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    },
    {
      "categoria": "Alimentos",
      "nombre": "Arroz",
      "cantidad": 5,
      "unidad": "kg",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    },
    {
      "categoria": "Alimentos",
      "nombre": "Azucar",
      "cantidad": 1,
      "unidad": "kg",
      "precio_unitario": 10.50,
      "precio_total_unidad": 10.50
    }
  ]
}
